### ISSUE TITLE
Import de prisma incorrecto en src/order-management/infraestructure/order.repository.ts

### ISSUE THREAD

**Issue by vSchiaffino** [DeveloperMartin/architecture-hexagonal-example#3]
Creo que hay un import travieso que se escapo en la tercer linea de [order.repository.ts](https://github.com/DeveloperMartin/architecture-hexagonal-example/blob/69966558eeac2f4d2b576f783f4182f9fd4c43f4/src/order-management/infraestructure/order.repository.ts) ya que importa prisma de la siguiente forma:

`
import prisma from '../../../dist/prisma/index';
`

creo que el import correcto es:

`
import prisma from '../../../prisma/index';
`

para utilizar el export del archivo [prisma/index.ts](https://github.com/DeveloperMartin/architecture-hexagonal-example/blob/69966558eeac2f4d2b576f783f4182f9fd4c43f4/prisma/index.ts)

**Comment by DeveloperMartin** [comment]
Es verdad!, buena observación.
